### ISSUE TITLE
[Kotlin] Add Kotlin Solution for Problem Of The Day

### ISSUE THREAD

**Issue by ImSaMPro** [AIOCodeBase/LCPOTD#400]

**Comment by ImSaMPro** [comment]
@chiragcode11

**Comment by chiragcode11** [comment]
`class Solution {
    fun isCompleteTree(root: TreeNode): Boolean {
    val Q: Queue = LinkedList()
    Q.offer(root)
    var flag = false
    while (!Q.isEmpty()) {
         val temp = Q.poll()
        if (temp == null) flag = true else {
            if (flag) return false
            Q.offer(temp.left)
            Q.offer(temp.right)
            }
        }
            return true
        }
    }`

**Comment by chiragcode11** [comment]
here is the tested code

**Comment by chiragcode11** [comment]
`class Solution {`
    `fun isCompleteTree(root: TreeNode): Boolean {`
   ` val Q: Queue = LinkedList()`
    `Q.offer(root)`
   ` var flag = false`
    `while (!Q.isEmpty()) {`
        ` val temp = Q.poll()`
       ` if (temp == null) flag = true else {`
            `if (flag) return false`
           ` Q.offer(temp.left)`
           ` Q.offer(temp.right)`
          `  }`
     `   }`
           ` return true`
      `  }`
    }`

**Comment by ImSaMPro** [comment]
@chiragcode11 where do you get the problem of the day for 20th March 2023)?
You have to solve the problem and run the code on the website once you tested the code you can create the pull request.

You will get the problem for this issue #400 on 20th March morning on the website itself. ([leetcode](https://leetcode.com/problemset/all/))

You can prefer YouTube videos if you don't know how GitHub works!
OR
Follow https://github.com/AIOCodeBase/LCPOTD/blob/main/CONTRIBUTING.md

**Comment by chiragcode11** [comment]
@ImSaMPro I got the problem from leetcode itself for 20th march and I tested the code and its successfull. on the other hand
 "LeatherHoard-Website" this directory is not present in your codebase, so I have made changes in problems and solution subfolder.And also I have created a pull request.

**Comment by chiragcode11** [comment]
you closed the PR that I created.

**Comment by ImSaMPro** [comment]
@chiragcode11 ,
I told you the problem will be available on 20th March 2023 not before the date!
Todays problem/20th march problem is available now! 
https://leetcode.com/problems/can-place-flowers/

Note make sure to sync your repository before modifying any code!
